import test from 'node:test';import assert from 'node:assert/strict';import {MicrosoftProvider} from '../public/integrations/microsoft.js';
function provider(fetchImpl){const p=new MicrosoftProvider({microsoftClientId:'11111111-1111-1111-1111-111111111111'},{fetchImpl});p.token=async()=> 'unit-test-only-token';p.me={id:'me',name:'Me'};return p;}
const response=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json',...headers}});
test('Graph requests reject untrusted hosts before token acquisition',async()=>{const p=provider(()=>{throw new Error('Must not fetch');});let tokens=0;p.token=async()=>{tokens++;return'not-used';};for(const url of ['https://evil.invalid/v1.0/me','https://graph.microsoft.com.evil.invalid/v1.0/me','https://user:pass@graph.microsoft.com/v1.0/me','https://graph.microsoft.com/beta/me'])await assert.rejects(p.request(url,['User.Read']),/Untrusted/);assert.equal(tokens,0);});
test('Graph mutation requests are never retried automatically',async()=>{let count=0;const p=provider(async()=>{count++;return response({error:{message:'Unavailable'}},503);});await assert.rejects(p.request('/chats',['Chat.Create'],{method:'POST',body:'{}'},true));assert.equal(count,1);});
test('Graph retry handles throttled GET only',async()=>{let count=0;const p=provider(async()=>++count===1?response({error:{message:'Throttle'}},429,{'Retry-After':'0'}):response({id:'me'}));assert.equal((await p.request('/me',['User.Read'])).id,'me');assert.equal(count,2);});
test('Graph nextLink host validation prevents bearer-token exfiltration',async()=>{let count=0;const p=provider(async()=>{count++;return response({value:[{id:'one'}],'@odata.nextLink':'https://evil.invalid/v1.0/me'});});await assert.rejects(p.pages('/me/chats',['Chat.Read']),/Untrusted/);assert.equal(count,1);});
test('consumer sign-in never calls unsupported Teams chat endpoints',async()=>{const p=provider(()=>{throw new Error('No request should occur');});p.personal=true;const data=await p.bootstrap();assert.deepEqual(data.rooms,[]);assert.equal(data.me.id,'me');});
test('Graph message identities stay distinct across conversations',()=>{const p=provider(()=>{}),raw={id:'123',body:{contentType:'text',content:'hello'},from:{user:{id:'a',displayName:'Alice'}},createdDateTime:'2026-09-08T09:00:00Z',reactions:[]};const a=p.normalizeMessage(raw,{id:'room-a',graphChatId:'a'}),b=p.normalizeMessage(raw,{id:'room-b',graphChatId:'b'});assert.notEqual(a.id,b.id);assert.equal(a.content,'hello');assert.equal(a.authorName,'Alice');});
test('calendar edits PATCH the existing Graph id instead of duplicating events',async()=>{let captured;const raw={id:'graph-existing',subject:'Edited',start:{dateTime:'2026-09-08T10:00:00',timeZone:'UTC'},end:{dateTime:'2026-09-08T11:00:00',timeZone:'UTC'},body:{contentType:'text',content:''}};const p=provider(async(url,opts)=>{captured={url,opts};return response(raw);});const original=p.calendarEvent(raw);const edited=await p.saveEvent({...original,title:'Edited'});assert.equal(captured.opts.method,'PATCH');assert.ok(captured.url.endsWith('/me/events/graph-existing'));assert.equal(edited.id,original.id);assert.equal(edited.start,'2026-09-08T10:00:00Z');assert.equal(captured.opts.headers.Prefer,'outlook.timezone="UTC"');});
test('Microsoft export includes no access tokens or MSAL account cache',async()=>{const p=provider(()=>{});p.msal={accessToken:'private-token-never-exported'};const exported=JSON.stringify(await p.export());assert.ok(!exported.includes('private-token'));assert.ok(!exported.includes('unit-test-only-token'));assert.ok(exported.includes('Loaded authorized records only'));});
